spring:
  cloud:
    gateway:
      routes:
        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**,/cookingStaff/**,/cleaningStaff/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**

        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: AUTH
          uri: http://localhost:7053
          predicates:
            - Path=/auth/**