spring:
  cloud:
    gateway:
      routes:
        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**,/cookingStaff/**,/cleaningStaff/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**

        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: AUTH
          uri: http://localhost:7053
          predicates:
            - Path=/auth/**

  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: ${OKTA_CLIENT_ID}
            client-secret: ${OKTA_CLIENT_SECRET}
            scope: openid, profile, email, groups, offline_access
            redirect-uri: http://localhost:7053/login/oauth2/code/okta

        provider:
          okta:
            issuer-uri: ${OKTA_ISSUER_URI}

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}