management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
otel:
  exporter:
    otlp:
      enabled: false
  propagation:
    type: w3c
logging:
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"
eureka:
    instance:
      prefer-ip-address: true
    client:
     fetch-registry: true
     register-with-eureka: true
     service-url:
      defaultZone: http://localhost:8761/eureka
