server:
  port: 7051

spring:
  application:
    name: rating-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"