spring:
  data:
    mongodb:
      uri: ${RATING_DB_URI}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OKTA_ISSUER_URI}

management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}